baseURL = "https://emilydoesastro.com"
languageCode = "en-us"
title = "Emily Lauren Hunt"
theme = "hugo-paradigm"
enableGitInfo = false
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = false
metaDataFormat = "yaml"
paginate = 6

[permalinks]
    post = "/:year/:month/:title/"

[taxonomies]
    tag = "tags"
    category = "categories"
    work =  "works"
    author = "authors"

[markup]
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ''
        hl_inline = false
        lineAnchors = ''
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = false
        noClasses = true
        noHl = false
        style = 'base16-snazzy'
        tabWidth = 4


  
# Main Menu
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

# [[menu.main]]
# 	name = "Custom Pages"
# 	url = "/custom-page-1"
#     weight = 2
#     identifier = 'dropdown'
#     [[menu.main]]
#         name = "Custom Page 1"
#         url = "/custom-page-1"
#         parent = "dropdown"
#         weight = 1
#     [[menu.main]]
#         name = "Custom Page 2"
#         url = "/custom-page-2"
#         parent = "dropdown"
#         weight = 2
#     [[menu.main]]
#         name = "Custom Page 3"
#         url = "/custom-page-3"
#         parent = "dropdown"
#         weight = 3
        
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 3

[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 4

[[menu.main]]
    name = "CV"
    url = "https://cv.emily.space"
    weight = 5
	
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 6


# Footer Menu Primary
[[menu.footer_primary]]
	name = "Home"
	url = "/"
    weight = 1
[[menu.footer_primary]]
	name = "Research"
	url = "/research/"
    weight = 2
[[menu.footer_primary]]
    name = "Blog"
    url = "/posts/"
    weight = 3
[[menu.footer_primary]]
    name = "About"
    url = "/about/"
    weight = 4

# Footer Menu Secondary
[[menu.footer_secondary]]
    name = "A better way to classify star clusters"
    url = "/posts/240311-gaia-cluster-masses/"
    weight = 1
[[menu.footer_secondary]]
    name = "My paper won a prize!"
    url = "/posts/231127-patzer-award/"
    weight = 2
[[menu.footer_secondary]]
    name = "How to get started on Bluesky"
    url = "/posts/230824-bluesky-signup/"
    weight = 3
