baseURL = "/"
languageCode = "en-us"
title = "Emily Lauren Hunt"
theme = "hugo-paradigm"
enableGitInfo = false
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
metaDataFormat = "yaml"
paginate = 6

[permalinks]
    post = "/:year/:month/:title/"

[taxonomies]
    tag = "tags"
    category = "categories"
    work =  "works"
    author = "authors"
  
# Main Menu
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

# [[menu.main]]
# 	name = "Custom Pages"
# 	url = "/custom-page-1"
#     weight = 2
#     identifier = 'dropdown'
#     [[menu.main]]
#         name = "Custom Page 1"
#         url = "/custom-page-1"
#         parent = "dropdown"
#         weight = 1
#     [[menu.main]]
#         name = "Custom Page 2"
#         url = "/custom-page-2"
#         parent = "dropdown"
#         weight = 2
#     [[menu.main]]
#         name = "Custom Page 3"
#         url = "/custom-page-3"
#         parent = "dropdown"
#         weight = 3
        
[[menu.main]]
    name = "My Research"
    url = "/research/"
    weight = 3

[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 4
	
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 5

# Footer Menu Primary
[[menu.footer_primary]]
	name = "Home"
	url = "/"
    weight = 1
[[menu.footer_primary]]
    name = "Blog"
    url = "/posts/"
    weight = 2
[[menu.footer_primary]]
    name = "Privacy Policy"
    url = "/privacy/"
    weight = 3

# Footer Menu Secondary
[[menu.footer_secondary]]
    name = "Custom Page 1"
    url = "/custom-page-1/"
    weight = 1

[[menu.footer_secondary]]
    name = "Custom Page 2"
    url = "/custom-page-2/"
    weight = 2
[[menu.footer_secondary]]
    name = "Custom Page 3"
    url = "/custom-page-3/"
    weight = 3