---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: content/_index.md
  label: Home
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
  templates:
  - page-custom
- type: directory
  path: content/features
  label: Features
  create: all
  match: "**/*"
  templates:
  - page-basic
  - page-custom
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - blog-page
  - page-basic
- type: directory
  path: data
  label: Data
  create: all
  match: "*.{yaml,yml,json,toml}"
- type: heading
  label: Configuation
- type: document
  path: data/themes.json
  label: Theme
- type: document
  path: data/layout.yaml
  label: Layout
- type: document
  path: data/seo.yaml
  label: SEO
- type: document
  path: config.toml
  label: Hugo Config
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.71.1
